{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyOJbpVLTjmxYOclW31OrkYB"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["# Φοιβη's Coding Class\n","## Lesson 11: Errors and Catching"],"metadata":{"id":"BaNAPwAtbkrj"}},{"cell_type":"markdown","source":["# Errors\n","By this point, you've probably seen python complain that an error has occurred at least once or twice. If not, run the cell below to generate a nice fresh error."],"metadata":{"id":"DoGz_KI_cBmH"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"VEsJOGXqbeLv"},"outputs":[],"source":["5 / 0"]},{"cell_type":"markdown","source":["Errors evolved in programming as a way to stop computers from having really nasty bugs crop up. Errors simply occur when you try to get a program to do something that its creators told it it's not allowed to do, so the program stops rather than pushing through and risking dangerous or unintentional issues.\n","\n","Now you'll notice that the Error is a specific ZeroDivisionError. This is because in python there is no real default error type. There are a variety of error types specific to different issues, far too many to go over right now, and the closest to default one (the one everyone uses) is RuntimeError."],"metadata":{"id":"WIILkLy7cTvu"}},{"cell_type":"markdown","source":["# Resolving Errors\n","Now you can probably see why it's a bad idea to just shut down the program everytime an error occurs. To avoid this, programming languages use something called \"try\" blocks. It's essentially a block of code that you can execute that will just move on if an error comes up. In python, you create a try block by typing `try:` and then any indented code following it will be part of the try block.\n"],"metadata":{"id":"TrwVb2U3pHOR"}},{"cell_type":"markdown","source":["## Catching\n","With every try block you need to have some resolution in the case that there is an error. It's generally considered such bad coding practice just to exit a program in the case of an error that python actually won't let you do it.\n","\n","A \"catch\" block is so named because it \"catches\" the error and does something to handle it. In python, since everything that could be renamed was, catch blocks are called \"except\" blocks.\n","\n","The simplest form for catch block just involves typing `except:` before a block of code that will execute if there is an error."],"metadata":{"id":"aoNiBkgrsDjK"}},{"cell_type":"code","source":["try:\n","  5 / 0\n","except:\n","  print(\"Error\")"],"metadata":{"id":"DnnEk21NuA-b"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["This obviously isn't super helpful since it doesn't tell us much about the error. The reason why these blocks are called \"catch\" blocks is that they can \"catch\" the error as a varriable itself.\n","\n","For example, to catch the error that we are making in this case:"],"metadata":{"id":"SJodNOjguBgv"}},{"cell_type":"code","source":["try:\n","  5 / 0\n","except ZeroDivisionError as e:\n","  print(e)"],"metadata":{"id":"vi9UMzXztNF3"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["One can also include multiple errors in a catch statement in parentheses:"],"metadata":{"id":"j3yWMqA3tf_v"}},{"cell_type":"code","source":["try:\n","  5 / 0\n","except (ZeroDivisionError, ValueError) as e:\n","  print(e)"],"metadata":{"id":"SQEjvwWEtkRL"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Or, if you want to handle different errors differently, in successive except blocks"],"metadata":{"id":"J6FH1pR9taaw"}},{"cell_type":"code","source":["try:\n","  5 / 0\n","except ValueError as e:\n","  print(e)\n","except ZeroDivisionError as e:\n","  print(\"The error is\", e)"],"metadata":{"id":"kkSY5dIfuytH"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### Exception\n","Or, if you want to be lazy, like the rest of us, you can use the statement `except Exception as e:`. All errors are children of the class `Exception` so this will catch all errors"],"metadata":{"id":"Hu_MTrdzu8WY"}},{"cell_type":"code","source":["try:\n","  5 / 0\n","except Exception as e:\n","  print(\"The error is\", e)"],"metadata":{"id":"yOTtz-YTu79a"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["## Finally\n","\n","Technically, after a try block, you don't have to have an except block. Instead you could use a finally block. The difference is that a finally block executes regardless of whether or not there is an error.\n","\n","The two aren't mutually exclusive though, and you can use except and finally blocks both after the same try block if you want."],"metadata":{"id":"KhzwEAX8sESh"}},{"cell_type":"code","source":["try:\n","  5 / 2\n","except Exception as e:\n","  print(\"The error is\", e)\n","finally:\n","  print(\"done\")"],"metadata":{"id":"r1l4eLavvRBc"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["# Raise\n","There will be times where you may want to create mark a process as having errored if something happens that shouldn't happen, but which isn't going to automatically create an error. In every other language I've worked with, this is called \"throwing\" an error, but in python, it's called \"raising an exception\".\n","\n","Bear in mind that errors are just class objects like any other, so to create one, you use the class initializer of the Error you want to, after the keyword raise within a try block. Often times the initializers work with no parameters, or with a string detailing the nature of the error.\n"],"metadata":{"id":"kjCzJIKbsGSz"}},{"cell_type":"code","source":["try:\n","  fav = input(\"type in your favorite color\")\n","  if (fav == \"green\"):\n","    raise RuntimeError(\"Green is not a creative color\")\n","except RuntimeError as e:\n","  print(\"Bad choice\")\n"],"metadata":{"id":"1aMuzV_pyn7G"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["## Customized Exceptions\n","You can also, if you're really feeling hardcore, create your own exceptions. The only thing you NEED to do is make sure the class extends the Exception class, but usually defining an initializer is good practice."],"metadata":{"id":"j86DWdcesIN0"}},{"cell_type":"code","source":["class MyError(Exception):\n","  def __init__(self, message):\n","    super().__init__(message)\n","\n","try:\n","  fav = 9\n","  raise MyError(\"Issues\")\n","except MyError as e:\n","  print(e)"],"metadata":{"id":"Z_I8SJjt0-vw"},"execution_count":null,"outputs":[]}]}